export const VALIDATION_USER_NAME_MIN_LENGTH = 6;
export const VALIDATION_USER_NAME_MAX_LENGTH = 50;
export const VALIDATION_USER_PASSWORD_MIN_LENGTH = 6;

export const VALIDATION_EVENT_NAME_MIN_LENGTH = 8;
export const VALIDATION_EVENT_NAME_MAX_LENGTH = 64;

export const VALIDATION_EVENT_DESCRIPTION_MIN_LENGTH = 8;
export const VALIDATION_EVENT_DESCRIPTION_MAX_LENGTH = 5000;

export const VALIDATION_REPORT_REASON_MIN_LENGTH = 15;
export const VALIDATION_REPORT_REASON_MAX_LENGTH = 100;

export const VALIDATION_REPORT_COMMENT_MIN_LENGTH = 15;
export const VALIDATION_REPORT_COMMENT_MAX_LENGTH = 100;

export const VALIDATION_EVENT_LOCATION_MAX_LENGTH = 30;
export const VALIDATION_EVENT_ORGANIZER_MAX_LENGTH = 30;
